### ISSUE TITLE
lda.b on snes.cpu error

### ISSUE THREAD

**Issue by hansbonini** [ARM9/bass#22] opened 2020-10-20 08:55 UTC
I have experienced some bytecode errors using `.b` statements on `snes.cpu`
Example:
```
lda.b       #$01
ldw         #$4300  // SNES.REG_DMAP0
```

Result:
```
lda        #$8D01
brk        #$43
```

Tested on bsnes-accuracy (debugger version)

**Comment by ARM9** [comment] 2020-10-20 10:03
There is no ldw instruction in the snes.cpu arch
`error: malformed expression: ldw #$4300`

**Comment by PeterLemon** [comment] 2020-10-20 16:09
Hi hansbonini,
It sounds like you are very inexperienced programming with the SNES CPU (65816). This is fine, but you should refrain from making issues when you do not have a proper idea of how things work! I suggest you read this programming document which will let you understand how 8/16-bit modes work, & what opcodes are available on the SNES CPU: https://wiki.nesdev.com/w/images/7/76/Programmanual.pdf

The SNES CPU arch in bass has been tested to be bit perfect for many years, & I have made multiple CPU tests on my github that run on real HW & emulators to test this & help emu authors: https://github.com/PeterLemon/SNES/tree/master/CPUTest/CPU

I am closing this issue now =D

**Closed by PeterLemon** 2020-10-20 16:09 UTC

**Comment by hansbonini** [comment] 2020-10-20 16:51
> I have experienced some bytecode errors using `.b` statements on `snes.cpu`
> Example:
> 
> ```
> lda.b       #$01
> sta         #$4300  // SNES.REG_DMAP0
> ```
> 
> Result:
> 
> ```
> lda        #$8D01
> brk        #$43
> ```
> 
> Tested on bsnes-accuracy (debugger version)

**Comment by ARM9** [comment] 2020-10-20 18:04
The instructions are encoding fine, the problem is that you're not using the right processor mode for that instruction sequence at runtime. You need to set the accumulator to 8 bit with `sep #$20`, you're setting the accumulator to 16 bit mode turning your `lda.b #$01` into `lda.w #$01+(next instruction<<8)` (note that both instructions encode to $A9, the processor status register changes the instructions behavior at runtime).

If you need help with snes programming try asking in https://discord.gg/uZ3p3D before opening another issue here.

**Comment by hansbonini** [comment] 2020-10-20 22:49
I was using `sep #$30` and `rep #$30`.
